on: [push]

jobs:
  dependency_analysis:
    runs-on:  ubuntu-latest
    name: Test depsendencies for security flaws
    steps:
      - uses: actions/checkout@v2
      - name:
        run: pip3 install safety && safety check
        shell: bash
